import './style.css';
import {createIcons, Workflow, FileCheck2, ChevronRight, Files, HardDrive, FilePlus2, FolderOpen, Download, FileDown, PencilLine, CloudCheck, ArrowLeft, ArrowRight, PanelRight, Maximize2, Lightbulb, Info, ImagePlus, Image as ImageIcon, Trash2, Upload, CopyCheck, Plus, ClipboardCheck, ScanLine, ArrowUpRight, X, FileText} from 'lucide';
import {emptyDocument,validateDocument,escapeHTML as esc,formatDate,completion,sections,connectionOptions,KEY,safeFilename,FORMAT_APPROVALS} from './model.js';
import {createPDF} from './pdf.js';

let doc=emptyDocument(), active=0, previewPage='plan', saveTimer, previewURL, imageBusy=false;
let storageWarning='';
try { const raw=localStorage.getItem(KEY);if(raw)doc=validateDocument(JSON.parse(raw)); } catch {storageWarning='No se pudo recuperar el borrador local. Puedes importar una copia guardada.';}
const $=selector=>document.querySelector(selector);
const icon=(name,size=18)=>`<i data-lucide="${name}" style="width:${size}px;height:${size}px" aria-hidden="true"></i>`;
const refreshIcons=()=>createIcons({icons:{Workflow,FileCheck2,ChevronRight,Files,HardDrive,FilePlus2,FolderOpen,Download,FileDown,PencilLine,CloudCheck,ArrowLeft,ArrowRight,PanelRight,Maximize2,Lightbulb,Info,ImagePlus,Image:ImageIcon,Trash2,Upload,CopyCheck,Plus,ClipboardCheck,ScanLine,ArrowUpRight,X,FileText}});
const input=(label,key,options={})=>`<label class="field ${options.wide?'wide':''}"><span>${label}${options.required?' <b class="required">*</b>':''}</span>${options.select?`<select data-field="${key}">${options.select.map(v=>`<option value="${esc(v)}" ${doc[key]===v?'selected':''}>${esc(v)}</option>`).join('')}</select>`:options.area?`<textarea data-field="${key}" rows="${options.rows||4}" maxlength="20000" placeholder="${esc(options.placeholder||'Escribe aquí…')}">${esc(doc[key])}</textarea>`:`<input data-field="${key}" type="${options.type||'text'}" value="${esc(doc[key])}" ${options.type==='number'?'min="0" step="any"':''} maxlength="${options.max||500}" placeholder="${esc(options.placeholder||'Sin completar')}" ${options.required?'aria-required="true"':''}>`}${options.help?`<small>${options.help}</small>`:''}</label>`;
const fieldGrid=content=>`<div class="fields">${content}</div>`;
const card=(title,subtitle,content)=>`<section class="card"><div class="card-heading"><h3>${title}</h3>${subtitle?`<p>${subtitle}</p>`:''}</div>${content}</section>`;
function toast(message,error=false){const el=$('#toast');el.textContent=message;el.className=`toast show ${error?'error':''}`;clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.classList.remove('show'),6000);}
function persist(){try{localStorage.setItem(KEY,JSON.stringify(doc));$('#save-state').textContent='Guardado en este navegador';}catch{$('#save-state').textContent='No se pudo guardar';toast('No hay espacio para guardar el borrador. Descarga una copia JSON.',true);}}
function changed(){ $('#save-state').textContent='Guardando…';clearTimeout(saveTimer);saveTimer=setTimeout(persist,400); updatePreview();updateProgress();}
function updateProgress(){const n=completion(doc);$('#progress-label').textContent=`${n} de 14 datos principales`;$('#progress-fill').style.width=`${n/14*100}%`;$('#document-name').textContent=doc.code||'Documento sin código';}
function renderShell(){
$('#app').innerHTML=`<aside class="sidebar"><a class="brand" href="./" aria-label="Swagelok Perú · Plan y Prueba"><span class="brand-mark">S</span><span class="brand-copy"><strong>Swagelok</strong><small>PERÚ · PLAN Y PRUEBA</small></span></a><div class="sidebar-group">HERRAMIENTA DE CALIDAD</div><div class="workspace-label">${icon('file-check-2')}<span>Plan y registro de prueba</span></div><nav aria-label="Secciones del documento">${sections.map((s,i)=>`<button class="nav-item ${i===active?'active':''}" data-section="${i}" ${i===active?'aria-current="step"':''}><span class="step-number">${i+1}</span><span>${s}</span>${icon('chevron-right',15)}</button>`).join('')}</nav><div class="sidebar-bottom"><div class="template-label">${icon('files')}<div>Sistema de calidad<small>Fuga y estanqueidad</small></div></div><p>Tus datos e imágenes se guardan en este navegador.</p><div class="local-label">${icon('hard-drive',14)} Almacenamiento local</div></div></aside>
<div class="app-main"><header class="topbar"><div class="breadcrumb">Swagelok Perú ${icon('chevron-right',14)} Documentos ${icon('chevron-right',14)} <strong id="document-name"></strong></div><div class="top-actions"><button class="btn quiet" data-action="new">${icon('file-plus-2')}<span>Nuevo</span></button><button class="btn quiet" data-action="import">${icon('folder-open')}<span>Abrir</span></button><button class="btn secondary" data-action="save">${icon('download')}<span>Guardar copia</span></button><button class="btn primary" data-action="export">${icon('file-down')}<span>Exportar PDF</span></button></div></header>
<main><div class="page-heading"><div><div class="eyebrow">SWAGELOK PERÚ <span> / </span> SISTEMAS INTEGRADOS <span> / </span> FR-6.3.2.9</div><h1>Planificación y registro técnico de pruebas</h1><p>Gestiona la trazabilidad de cada prueba de fuga y estanqueidad desde una sola herramienta.</p></div><span class="draft-badge">${icon('pencil-line',13)} Borrador</span></div>
<div class="workspace"><div class="editor-column"><div class="section-heading"><div><span id="section-kicker" class="eyebrow"></span><h2 id="section-title"></h2></div><span class="save-status">${icon('cloud-check',15)}<span id="save-state">Guardado en este navegador</span></span></div><div id="editor"></div><div class="editor-footer"><button class="btn secondary" data-action="previous">${icon('arrow-left')} Anterior</button><span id="step-label"></span><button class="btn primary" data-action="next">Continuar ${icon('arrow-right')}</button></div></div>
<aside class="preview-column" aria-label="Vista previa del documento"><div class="preview-heading"><div>${icon('panel-right',17)}<h3>Vista previa</h3></div><button class="icon-btn" data-action="preview" title="Abrir vista previa exacta del PDF" aria-label="Abrir vista previa exacta del PDF">${icon('maximize-2')}</button></div><div class="preview-tabs"><button data-preview="plan" class="selected">01 · Plan</button><button data-preview="record">02 · Registro</button></div><div id="paper-container"></div><div class="preview-caption">A4 · Vista resumida <button data-action="preview">Ver PDF completo ${icon('arrow-up-right',12)}</button></div><div class="completion-card"><div><strong>Avance del documento</strong><span id="progress-label"></span></div><div class="progress-track"><div id="progress-fill"></div></div><p>Los campos pendientes permanecerán en blanco en el PDF.</p></div><div class="tip">${icon('lightbulb',18)}<p>Completa los datos una sola vez. El plan y el registro comparten la información de la integración.</p></div></aside></div></main><footer class="app-footer"><span>SWAGELOK PERÚ · PLAN & PRUEBA</span><span>Control documental para sistemas integrados.</span></footer></div>
<input type="file" id="import-file" accept="application/json,.json" hidden><div id="toast" class="toast" role="status" aria-live="polite"></div><dialog id="modal"></dialog>`;
renderEditor();updatePreview();updateProgress();refreshIcons();
}
function renderEditor(){
$('#section-kicker').textContent=`PASO 0${active+1} DE 05`;
$('#section-title').textContent=sections[active];$('#step-label').textContent=`${active+1} / 5`;
$('[data-action="previous"]').disabled=active===0;
$('[data-action="next"]').innerHTML=active===4?`Revisar y exportar ${icon('file-down')}`:`Continuar ${icon('arrow-right')}`;
document.querySelectorAll('[data-section]').forEach(b=>{b.classList.toggle('active',Number(b.dataset.section)===active);if(Number(b.dataset.section)===active)b.setAttribute('aria-current','step');else b.removeAttribute('aria-current');});
let content='';
if(active===0){content=card('Información de la integración','Estos datos aparecerán en el plan y en el registro.',fieldGrid(input('Nombre del cliente','client',{wide:true,required:true,placeholder:'Nombre o razón social del cliente'})+input('Código de la integración','code',{required:true,placeholder:'Ej. INT-2026-001'})+input('Identificador','identifier',{placeholder:'Serie o identificador del sistema'})+input('Cantidad','quantity',{type:'number'})+input('Fecha','date',{type:'date',required:true})+input('Nota de pedido','order',{placeholder:'Ej. NP-0042'})+input('Orden de producción','production',{placeholder:'Ej. OP-0128'})))+`<div class="inline-note">${icon('info')}<p><strong>Una base para ambas hojas.</strong> Puedes exportar el plan, el registro o el documento completo en cualquier momento. <span>Los asteriscos identifican los datos principales.</span></p></div>`;}
if(active===1){content=card('Imagen del ensamblaje','Carga el diagrama o una fotografía con las conexiones enumeradas.',`<div class="upload-zone ${doc.image?'has-image':''}" id="drop-zone">${doc.image?`<img src="${doc.image.data}" alt="Imagen del ensamblaje"><div class="image-info"><span>${icon('image',16)} ${esc(doc.image.name)}</span><button class="btn quiet danger" data-action="remove-image">${icon('trash-2',15)} Quitar</button></div>`:`<span class="upload-icon">${icon('image-plus',30)}</span><h4>Arrastra aquí tu ensamblaje</h4><p>o selecciona una imagen de tu equipo</p>`}<label class="btn secondary file-button" tabindex="0">${icon('upload',16)} ${doc.image?'Cambiar imagen':'Seleccionar imagen'}<input id="image-file" type="file" accept="image/png,image/jpeg,image/webp" hidden></label><small>JPG, PNG o WebP · hasta 10 MB</small></div>`)+card('Leyenda de la plantilla','Usa estas referencias al preparar tu diagrama.',`<div class="legend-grid">${[['C','Válvula cerrada'],['A','Válvula abierta'],['M','Manómetro'],['R','Regulador']].map(([s,l])=>`<div><b>${s}</b><span>${l}</span></div>`).join('')}</div>`)+`<div class="inline-note">${icon('copy-check')}<p>La misma imagen aparecerá en las dos hojas. Se ajustará al espacio disponible conservando sus proporciones.</p></div>`;}
if(active===2){content=card('Condiciones propuestas','Define los parámetros y el procedimiento del plan.',fieldGrid(input('Presión propuesta','pressure',{type:'number',placeholder:'Ej. 100'})+input('Unidad de presión','pressureUnit',{select:['PSI','bar','kPa','MPa']})+input('Duración propuesta','duration',{placeholder:'Ej. 10 minutos'})+input('Método','method',{placeholder:'Ej. Detección con solución'})+input('Gas de prueba','gas',{select:['Nitrógeno','Otro']})+(doc.gas==='Otro'?input('Especifica el gas','otherGas'):'')))+card('Procedimiento y notas','Introduce el procedimiento definido para esta integración.',fieldGrid(input('Secuencia de tareas e instrucciones','instructions',{area:true,wide:true,rows:6,placeholder:'Describe la preparación, la secuencia y los criterios de la prueba…'})+input('Notas del plan','planNotes',{area:true,wide:true,rows:3})))+card('Responsables del plan','',fieldGrid(input('Realizado por','planBy')+input('Revisado por','planReviewer')));}
if(active===3){content=card('Condiciones de la prueba','Registra los valores realmente utilizados.',fieldGrid(input('Presión suministrada','actualPressure',{type:'number'})+input('Unidad de presión','actualUnit',{select:['PSI','bar','kPa','MPa']})+input('Método utilizado','actualMethod')+input('Gas utilizado','actualGas',{select:['Nitrógeno','Otro']})+(doc.actualGas==='Otro'?input('Especifica el gas','actualOtherGas'):'')+input('Hora de inicio','start',{type:'time'})+input('Hora de finalización','end',{type:'time'})))+card('Inspección de conexiones','Selecciona el resultado de cada conexión enumerada en el diagrama.',`<div class="connection-grid">${doc.connections.map((v,i)=>`<label class="connection ${statusClass(v)}"><span>${String(i+1).padStart(2,'0')}</span><select data-connection="${i}" aria-label="Resultado de conexión ${i+1}">${connectionOptions.map(o=>`<option ${o===v?'selected':''}>${o}</option>`).join('')}</select></label>`).join('')}</div><div class="connection-count">${doc.connections.filter(v=>v==='Conforme').length} conformes · ${doc.connections.filter(v=>v==='No conforme').length} no conformes · ${doc.connections.filter(v=>v==='Pendiente').length} pendientes</div>`)+card('Correcciones','Registra las intervenciones y su inspección.',fieldGrid(input('¿Se requiere corregir alguna conexión?','needsCorrection',{select:['Pendiente','Sí','No'],wide:true}))+renderRows('corrections')+`<button class="btn secondary add-row" data-action="add-correction">${icon('plus',16)} Añadir corrección</button>`)+card('Equipo de medición utilizado','',renderRows('equipment')+`<button class="btn secondary add-row" data-action="add-equipment">${icon('plus',16)} Añadir equipo</button>`)+card('Resultado y responsables','',fieldGrid(input('Resultado de la prueba','result',{select:['Pendiente','Aprobado','Rechazado'],wide:true})+input('Motivo','reason',{area:true,wide:true,rows:2})+input('Notas del registro','recordNotes',{area:true,wide:true,rows:3})+input('Realizado por','recordBy')+input('Inspeccionado por','inspector')));}
if(active===4){content=card('Identificación del formato','',fieldGrid(input('Organización','organization',{wide:true})+input('Código del formato','formCode',{max:40})+input('Versión','version',{max:20})))+card('Historial del documento','',fieldGrid(input('Número de revisión','revision')+input('Fecha de actualización','revisionDate',{type:'date'})+input('Descripción del cambio','change',{area:true,wide:true,rows:3})))+card('Elaboración, revisión y aprobación','Información fija del formato original. Se conserva en ambas hojas y no es editable.',renderRows('approvals'))+`<div class="inline-note">${icon('clipboard-check')}<p>El documento se genera con los datos que hayas completado. Revisa el PDF antes de distribuirlo.</p></div>`;}
$('#editor').innerHTML=content;refreshIcons();setupDrop();
}
function statusClass(v){return v==='Conforme'?'pass':v==='No conforme'?'fail':v==='No aplica'?'na':'';}
function renderRows(key){
if(key==='approvals')return FORMAT_APPROVALS.map(row=>`<div class="row-card"><div class="row-title"><strong>${esc(row.role)}</strong><span>Información del formato · Solo lectura</span></div><dl class="format-approval">${[['Cargo',row.position],['Nombre',row.name],['Fecha',row.date],['Firma',row.status]].map(([label,value])=>`<div><dt>${label}</dt><dd>${esc(value)}</dd></div>`).join('')}</dl></div>`).join('');
const fields={corrections:[['connection','Conexión'],['responsible','Responsable'],['date','Fecha de corrección','date'],['inspector','Inspector'],['inspectionDate','Fecha de inspección','date'],['compliant','¿Cumple?',['Pendiente','Sí','No']]],equipment:[['name','Nombre y código'],['expiry','Vencimiento de calibración','date']],approvals:[['position','Cargo'],['name','Nombre'],['date','Fecha','date'],['status','Estado',['Pendiente','Autorizado','Rechazado']]]}[key];
if(!doc[key].length)return `<p class="empty-rows">${key==='corrections'?'Sin correcciones registradas.':'Sin equipos registrados.'}</p>`;
return doc[key].map((row,i)=>`<div class="row-card"><div class="row-title"><strong>${key==='approvals'?esc(row.role):`${key==='equipment'?'Equipo':'Corrección'} ${i+1}`}</strong>${key!=='approvals'?`<button class="icon-btn danger" data-remove="${key}" data-index="${i}" aria-label="Eliminar ${key==='equipment'?'equipo':'corrección'} ${i+1}">${icon('trash-2',16)}</button>`:''}</div><div class="fields">${fields.map(([f,l,t])=>`<label class="field"><span>${l}</span>${Array.isArray(t)?`<select data-row="${key}" data-index="${i}" data-key="${f}">${t.map(v=>`<option ${v===row[f]?'selected':''}>${v}</option>`).join('')}</select>`:`<input data-row="${key}" data-index="${i}" data-key="${f}" type="${t||'text'}" maxlength="2000" value="${esc(row[f])}">`}</label>`).join('')}</div></div>`).join('');
}
function updatePreview(){
const val=v=>esc(v||'—');const isPlan=previewPage==='plan';
$('#paper-container').innerHTML=`<div class="paper"><div class="paper-header"><div class="paper-logo">SW<span>+</span></div><div>SISTEMA DE CONTROL DE LA CALIDAD<strong>${isPlan?'PLAN':'REGISTRO'} DE PRUEBA</strong><span>Fuga y/o estanqueidad de sistemas integrados</span></div><small>${val(doc.formCode)}<br>Versión ${val(doc.version)}</small></div><div class="paper-meta">${[['Cliente',doc.client],['Integración',doc.code],['Fecha',formatDate(doc.date)],['Cantidad',doc.quantity],['Nota de pedido',doc.order],['O. de producción',doc.production]].map(([k,v])=>`<div><span>${k}</span><strong>${val(v)}</strong></div>`).join('')}</div><div class="paper-conditions"><div>Presión<strong>${val(isPlan?doc.pressure:doc.actualPressure)} ${val(isPlan?doc.pressureUnit:doc.actualUnit)}</strong></div><div>${isPlan?'Duración':'Inicio / fin'}<strong>${val(isPlan?doc.duration:doc.start+' / '+doc.end)}</strong></div><div>Gas<strong>${val(isPlan?(doc.gas==='Otro'?doc.otherGas:doc.gas):(doc.actualGas==='Otro'?doc.actualOtherGas:doc.actualGas))}</strong></div></div><h4>ENSAMBLAJE</h4><div class="paper-image">${doc.image?`<img src="${doc.image.data}" alt="Ensamblaje en la vista resumida">`:`${icon('scan-line',30)}<span>Tu imagen de ensamblaje aparecerá aquí</span>`}</div>${isPlan?`<div class="paper-legend">C · Cerrada &nbsp; A · Abierta &nbsp; M · Manómetro &nbsp; R · Regulador</div><h4>SECUENCIA DE TAREAS</h4><p class="paper-text">${val(doc.instructions)}</p><h4>NOTAS</h4><p class="paper-text small">${val(doc.planNotes)}</p>`:`<h4>INSPECCIÓN DE CONEXIONES</h4><div class="paper-connections">${doc.connections.map((s,i)=>`<span class="${statusClass(s)}">${i+1}<b>${s==='Conforme'?'C':s==='No conforme'?'NC':s==='No aplica'?'NA':'—'}</b></span>`).join('')}</div><div class="paper-result">Resultado de la prueba <strong>${val(doc.result)}</strong></div>`}<div class="paper-signs"><div>${val(isPlan?doc.planBy:doc.recordBy)}<span>Realizado por</span></div><div>${val(isPlan?doc.planReviewer:doc.inspector)}<span>${isPlan?'Revisado':'Inspeccionado'} por</span></div></div><div class="paper-bottom"><span>${val(doc.formCode)} · Copia no controlada</span><span>${isPlan?'01':'02'}</span></div></div>`;refreshIcons();
}
function showModal(html,wide=false){const modal=$('#modal');modal.className=wide?'large-modal':'';modal.innerHTML=html;modal.showModal();refreshIcons();}
function exportModal(){showModal(`<div class="modal-heading"><div><span class="eyebrow">DOCUMENTO LISTO PARA GENERAR</span><h2>Exportar a PDF</h2></div><button class="icon-btn" data-action="close" aria-label="Cerrar">${icon('x')}</button></div><p>Elige las hojas que quieres descargar.</p><div class="export-options">${[['both','Documento completo','Plan y registro de prueba'],['plan','Solo el plan','Condiciones e instrucciones'],['record','Solo el registro','Resultados, correcciones y equipos']].map(([v,t,s],i)=>`<label><input type="radio" name="export-selection" value="${v}" ${i===0?'checked':''}><span><strong>${t}</strong><small>${s}</small></span>${icon('file-text',22)}</label>`).join('')}</div><div class="inline-note compact">${icon('info',18)}<p>${completion(doc)<14?'Hay datos pendientes. Puedes exportar esta hoja como plantilla y completarla después.':'Revisa la información antes de distribuir el documento.'}</p></div><div class="modal-actions"><button class="btn secondary" data-action="close">Cancelar</button><button class="btn primary" data-action="download-pdf">${icon('download')} Descargar PDF</button></div>`);}
async function showPreview(){try{toast('Preparando vista previa…');await new Promise(r=>setTimeout(r,30));if(previewURL)URL.revokeObjectURL(previewURL);previewURL=URL.createObjectURL(createPDF(doc).output('blob'));showModal(`<div class="modal-heading"><h2>Vista previa del PDF</h2><button class="icon-btn" data-action="close" aria-label="Cerrar">${icon('x')}</button></div><iframe title="PDF completo del plan y registro" src="${previewURL}"></iframe><div class="modal-actions"><a class="btn secondary" href="${previewURL}" target="_blank" rel="noopener">Abrir en otra pestaña</a><a class="btn primary" href="${previewURL}" download="${safeFilename(doc)}">${icon('download')} Descargar PDF</a></div>`,true);}catch(e){toast('No se pudo generar el PDF. '+e.message,true);}}
function download(data,filename,type){const url=URL.createObjectURL(new Blob([data],{type}));const a=document.createElement('a');a.href=url;a.download=filename;a.click();setTimeout(()=>URL.revokeObjectURL(url),30000);}
async function loadImage(file){
if(!file||imageBusy)return;
if(!['image/png','image/jpeg','image/webp'].includes(file.type)){toast('Selecciona una imagen JPG, PNG o WebP.',true);return;}
if(file.size>10*1024*1024){toast('La imagen supera el límite de 10 MB.',true);return;}
imageBusy=true;toast('Preparando imagen…');let url;
try{url=URL.createObjectURL(file);const img=new Image();img.src=url;await img.decode();if(img.width*img.height>50000000)throw new Error('La imagen es demasiado grande. Reduce sus dimensiones.');const ratio=Math.min(1,2000/Math.max(img.width,img.height));const canvas=document.createElement('canvas');canvas.width=Math.round(img.width*ratio);canvas.height=Math.round(img.height*ratio);const ctx=canvas.getContext('2d');ctx.fillStyle='#fff';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.drawImage(img,0,0,canvas.width,canvas.height);doc.image={data:canvas.toDataURL('image/jpeg',.88),width:canvas.width,height:canvas.height,name:file.name.slice(0,300)};changed();renderEditor();toast('Ensamblaje incorporado a las dos hojas.');}catch(e){toast(e.message.includes('dimensiones')?e.message:'No se pudo leer la imagen. Prueba con otro archivo.',true);}finally{imageBusy=false;if(url)URL.revokeObjectURL(url);}
}
function setupDrop(){const zone=$('#drop-zone');if(!zone)return;zone.addEventListener('dragover',e=>{e.preventDefault();zone.classList.add('dragover');});zone.addEventListener('dragleave',()=>zone.classList.remove('dragover'));zone.addEventListener('drop',e=>{e.preventDefault();zone.classList.remove('dragover');loadImage(e.dataTransfer.files[0]);});}
function navigate(index){active=Math.max(0,Math.min(4,index));renderEditor();$('#section-title').scrollIntoView({behavior:'smooth',block:'start'});}
document.addEventListener('input',e=>{const t=e.target;if(t.dataset.field){doc[t.dataset.field]=t.value;changed();}else if(t.dataset.row){doc[t.dataset.row][Number(t.dataset.index)][t.dataset.key]=t.value;changed();}});
document.addEventListener('change',async e=>{const t=e.target;
if(['gas','actualGas'].includes(t.dataset.field)){renderEditor();}
if(t.dataset.connection!==undefined){doc.connections[Number(t.dataset.connection)]=t.value;changed();t.closest('.connection').className=`connection ${statusClass(t.value)}`;$('.connection-count').textContent=`${doc.connections.filter(v=>v==='Conforme').length} conformes · ${doc.connections.filter(v=>v==='No conforme').length} no conformes · ${doc.connections.filter(v=>v==='Pendiente').length} pendientes`;}
if(t.id==='image-file')loadImage(t.files[0]);
if(t.id==='import-file'){const file=t.files[0];t.value='';if(!file)return;try{if(file.size>6000000)throw new Error('El archivo supera los 6 MB.');const parsed=validateDocument(JSON.parse(await file.text()));window.pendingImport=parsed;showModal(`<div class="modal-heading"><h2>Abrir documento</h2></div><p>Se reemplazará el borrador actual por <strong>${esc(parsed.code||file.name)}</strong>. Guarda una copia si quieres conservar el actual.</p><div class="modal-actions"><button class="btn secondary" data-action="close">Cancelar</button><button class="btn secondary" data-action="save">Guardar copia actual</button><button class="btn primary" data-action="confirm-import">Abrir documento</button></div>`);}catch(e){toast(e.message||'No se pudo abrir el archivo.',true);}}
});
document.addEventListener('keydown',e=>{if(e.target.matches('.file-button')&&(e.key==='Enter'||e.key===' ')){e.preventDefault();$('#image-file').click();}});
document.addEventListener('click',async e=>{const section=e.target.closest('[data-section]');if(section){navigate(Number(section.dataset.section));return;}const p=e.target.closest('[data-preview]');if(p){previewPage=p.dataset.preview;document.querySelectorAll('[data-preview]').forEach(b=>b.classList.toggle('selected',b===p));updatePreview();return;}
const remove=e.target.closest('[data-remove]');if(remove){doc[remove.dataset.remove].splice(Number(remove.dataset.index),1);renderEditor();changed();return;}
const b=e.target.closest('[data-action]');if(!b)return;
switch(b.dataset.action){
case 'next':active===4?exportModal():navigate(active+1);break;
case 'previous':navigate(active-1);break;
case 'save':download(JSON.stringify(doc,null,2),safeFilename(doc).replace('.pdf','.json'),'application/json');toast('Copia editable descargada.');break;
case 'import':$('#import-file').click();break;
case 'export':exportModal();break;
case 'preview':showPreview();break;
case 'close':$('#modal').close();break;
case 'download-pdf':try{b.disabled=true;b.textContent='Generando…';await new Promise(r=>setTimeout(r,30));const choice=$('input[name="export-selection"]:checked').value;createPDF(doc,choice).save(safeFilename(doc).replace('.pdf',choice==='both'?'.pdf':`-${choice==='plan'?'plan':'registro'}.pdf`));$('#modal').close();toast('PDF generado correctamente.');}catch(err){toast('No se pudo generar el PDF. '+err.message,true);}finally{b.disabled=false;b.textContent='Descargar PDF';}break;
case 'remove-image':doc.image=null;renderEditor();changed();break;
case 'add-correction':if(doc.corrections.length>=100){toast('El límite es de 100 correcciones.',true);break;}doc.corrections.push({connection:'',responsible:'',date:'',inspector:'',inspectionDate:'',compliant:'Pendiente'});renderEditor();changed();break;
case 'add-equipment':if(doc.equipment.length>=100){toast('El límite es de 100 equipos.',true);break;}doc.equipment.push({name:'',expiry:''});renderEditor();changed();break;
case 'new':showModal(`<div class="modal-heading"><h2>Crear un nuevo documento</h2></div><p>Se vaciará el borrador actual. Guarda una copia para poder volver a abrirlo después.</p><div class="modal-actions"><button class="btn secondary" data-action="close">Cancelar</button><button class="btn secondary" data-action="save">Guardar copia</button><button class="btn primary" data-action="confirm-new">Crear nuevo</button></div>`);break;
case 'confirm-new':doc=emptyDocument();active=0;$('#modal').close();renderEditor();changed();toast('Nuevo documento creado.');break;
case 'confirm-import':if(window.pendingImport){doc=window.pendingImport;delete window.pendingImport;active=0;$('#modal').close();renderEditor();changed();toast('Documento abierto.');}break;
}
});
renderShell();if(storageWarning)toast(storageWarning,true);
window.addEventListener('pagehide',()=>{clearTimeout(saveTimer);try{localStorage.setItem(KEY,JSON.stringify(doc));}catch{}});
if(document.modelContext?.registerTool){try{
const register=tool=>Promise.resolve(document.modelContext.registerTool(tool)).catch(()=>{});
register({name:'read_test_document',description:'Read the current plan and test record, excluding assembly image bytes.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:()=>({...doc,image:doc.image?{name:doc.image.name,width:doc.image.width,height:doc.image.height}:null})});
const fields=Object.keys(emptyDocument()).filter(k=>typeof doc[k]==='string');
register({name:'update_test_document_fields',description:'Update and locally save the supplied text fields in the current plan and test record. This does not export, approve or sign the document.',inputSchema:{type:'object',properties:{fields:{type:'object',properties:Object.fromEntries(fields.map(k=>[k,{type:'string',maxLength:20000}])),additionalProperties:false}},required:['fields'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:true},execute:input=>{if(!input?.fields||typeof input.fields!=='object'||Array.isArray(input.fields)||Object.keys(input.fields).some(k=>!fields.includes(k)))throw new Error('Invalid document fields');const next=validateDocument({...doc,...input.fields});doc=next;renderEditor();updatePreview();updateProgress();persist();return{updatedFields:Object.keys(input.fields),code:doc.code};}});
}catch{/* Optional browser API. */}}
